#this is the constraints.xdc file used for synthesizing design and generation bitstream to test on FPGA board(BASYS 3)
# Clock signal
set_property PACKAGE_PIN W5 [get_ports clk]							
	set_property IOSTANDARD LVCMOS33 [get_ports clk]
	create_clock -add -name sys_clk_pin -period 10.00 -waveform {0 5} [get_ports clk]
 
# Switches
set_property PACKAGE_PIN V17 [get_ports {a_in[0]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {a_in[0]}]
set_property PACKAGE_PIN V16 [get_ports {a_in[1]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {a_in[1]}]
set_property PACKAGE_PIN W16 [get_ports {a_in[2]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {a_in[2]}]
set_property PACKAGE_PIN W17 [get_ports {a_in[3]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {a_in[3]}]
set_property PACKAGE_PIN V15 [get_ports {b_in[0]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {b_in[0]}]
set_property PACKAGE_PIN W14 [get_ports {b_in[1]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {b_in[1]}]
set_property PACKAGE_PIN W13 [get_ports {b_in[2]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {b_in[2]}]
set_property PACKAGE_PIN V2 [get_ports {b_in[3]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {b_in[3]}]

# LEDs
set_property PACKAGE_PIN U16 [get_ports {result[0]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {result[0]}]
set_property PACKAGE_PIN E19 [get_ports {result[1]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {result[1]}]
set_property PACKAGE_PIN U19 [get_ports {result[2]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {result[2]}]
set_property PACKAGE_PIN V19 [get_ports {result[3]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {result[3]}]
set_property PACKAGE_PIN W18 [get_ports {result[4]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {result[4]}]
set_property PACKAGE_PIN U15 [get_ports {result[5]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {result[5]}]
set_property PACKAGE_PIN U14 [get_ports {result[6]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {result[6]}]
set_property PACKAGE_PIN V14 [get_ports {result[7]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {result[7]}]

set_property PACKAGE_PIN L1 [get_ports {done}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {done}]

###Buttons
set_property PACKAGE_PIN W19 [get_ports rst]						
	set_property IOSTANDARD LVCMOS33 [get_ports rst]
set_property PACKAGE_PIN T17 [get_ports start]						
	set_property IOSTANDARD LVCMOS33 [get_ports start]
